<?php
/**
 * 注意，这里是通用的缓存Key配置文件，原则上不允许自行修改！
 * 通用配置是适合所有客户端或者绝大多数客户端使用。如果需要为某个或者某几个客户端做独立的配置，尤其是会影响到其它客户端的配置，请单独填写并单独加载！
 */

// 数组第二个参数 1开启映射 0关闭映射 第三个参数如果memcache里没有，redis里有，是否缓存到memcache 0不缓存 1缓存
return array(
    'cachemap' => array(
		'index_zxgx'			=>  array('index_last_booklist', 1, 1),
		'index_rmtj'			=>  array('txtxiaoshuo_bangindex_rmtj_newhongshu', 1, 1),//首页热门推荐
		'index_link'			=>  array('txtxiaoshuo_bangstatic_index_friendlink', 1, 1),
		'index_nanqt'			=>  array('txtxiaoshuo_bangindex_nanqt_newhongshu', 1, 1), //首页-男生强推
		'calss_nanqt'			=>  array('txtxiaoshuo_bangclass_nan_nsqt_newhongshu', 1, 1), //男频-男生强推
		'index_nvqt'			=>  array('txtxiaoshuo_bangindex_nvqt_newhongshu', 1, 1), //首页-女生强推
		'index_nanhp'			=>  array('txtxiaoshuo_bangauto_index_nan_redticket', 1, 1),
		'index_nvhp'			=>  array('txtxiaoshuo_bangauto_index_nv_redticket', 1, 1),
		'index_nanft'			=>  array('txtxiaoshuo_bangindex_nanft_newhongshu', 1, 1),//男封推
		'index_nvft'			=>  array('txtxiaoshuo_bangindex_nvft_newhongshu', 1, 1),//女封推
		'index_dszq'			=>  array('txtxiaoshuo_index_dashen_newhongshu', 0, 0),   //首页大神专区
		'index_wbzq'			=>  array('txtxiaoshuo_index_wanben_newhongshu', 0, 0),   //首页完本专区
		'index_notice'			=>  array('txtxiaoshuo_bangstatic_index_rmtj', 1, 1),
		'index_nanmf'			=>  array('txtxiaoshuo_bangauto_index_nanmf', 1, 1),
		'index_nvmf'			=>  array('txtxiaoshuo_bangauto_index_nvmf', 1, 1),
		'index_nandft'          =>  array('txtxiaoshuo_bangclass_nandft_newhongshu',1,1),//男大封推
		'index_nvdft'           =>  array('txtxiaoshuo_bangclass_nvdft_newhongshu',1,1),//女大封推
		'index_nanrm'			=>  array('txtxiaoshuo_bangclass_nan_rmtj_newhongshu', 1, 1),//男频-热门推荐
		'index_nvrm'			=>  array('txtxiaoshuo_bangclass_nv_rmtj_newhongshu', 1, 1),//女频-热门推荐
		'index_nanjp'			=>  array('txtxiaoshuo_bangclass_nan_jptj_newhongshu', 1, 1),//男生精品推荐
		'index_nvjp'			=>  array('txtxiaoshuo_bangclass_nv_jptj_newhongshu', 1, 1),//女生精品推荐
		'book_normal#'			=>  array('txtxiaoshuo_book_', 1, 1),
		'chpt_normal#'			=>  array('txtxiaoshuo_chpt_', 1, 1),
		'book_fensi#'			=>  array('txtxiaoshuo:bookfensi:', 1, 0),
		'author_booklist#'		=>  array('author_booklist_', 1, 1),
		'booktrend#'			=>  array('txtxiaoshuo:booktrend:', 0, 1),
		'txtxiaoshuo:booktrend#'=>  array('txtxiaoshuo:booktrend:', 1, 0),
		'index_nanptj'			=>  array('txtxiaoshuo_bangindex_nstj', 1, 1),
		'index_nvptj'			=>  array('txtxiaoshuo_bangindex_yqtj', 1, 1),
		'flowerranking_nan'		=>  array('txtxiaoshuo_bangauto_top_nan_monthflower', 1, 1),
		'flowerranking_nv'		=>  array('txtxiaoshuo_bangauto_top_nv_monthflower', 1, 1),
		'breakword_comment'		=>  array('txtxiaoshuo_badwordcommentcontent', 1, 1),
		'breakword_comment2'	=>  array('txtxiaoshuo_badwordcommentcontent2', 1, 1),
		'breakword_content'		=>  array('txtxiaoshuo_badwordcontent', 1, 1),
		'breakword_username'	=>  array('txtxiaoshuo_badwordusername', 1, 1),
		'user_normal#'			=>  array(':userinfo:', 1, 1),
		'bookfans_normal#'		=>  array('txtxiaoshuo:bookfensi:', 1, 1),
		'commentset#'			=>  array('txtxiaoshuo:comset:', 1, 1),
		'bookrank#'				=>  array('txtxiaoshuo:booktop:', 1, 1),
		'index_nan_wenzi'       =>  array('txtxiaoshuo_bangindex_nan_wenzi',1,1),//首页男文字推
		'index_nv_wenzi'        =>  array('txtxiaoshuo_bangindex_nv_wenzi',1,1),//首页女文字推
		'class_nan_upwenzi'     =>  array('txtxiaoshuo_bangclass_nan_wenzi_up',1,1),//男频文字榜 上部
		'class_nan_downwenzi'   =>  array('txtxiaoshuo_bangclass_nan_wenzi_down',1,1), //男频文字榜 下部
		'class_nv_upwenzi'      =>  array('txtxiaoshuo_bangclass_nv_wenzi_up',1,1), //女频文字榜 上部
		'class_nv_downwenzi'    =>  array('txtxiaoshuo_bangclass_nv_wenzi_down',1,1),//女频文字榜 下部
		'index_gonggao'     	=>  array('txtxiaoshuo_bangstatic_newgonggao_index',1,1), //通用公告
		'index_nan_gonggao' 	=>  array('txtxiaoshuo_bangstatic_newgonggao_nan',1,1), //男频首页
		'index_nv_gonggao'  	=>  array('txtxiaoshuo_bangstatic_newgonggao_nv',1,1),   //女频首页
		'index_fansrecom'   	=>  array('txtxiaoshuo_bangindex_fensi_newhongshu',1,1), //首页粉丝榜
		'index_nan_fensi'   	=>  array('txtxiaoshuo_bangindex_fensi_nan_newhongshu',1,1),//男频粉丝榜
		'index_nv_fensi'    	=>  array('txtxiaoshuo_bangindex_fensi_nv_newhongshu',1,1), ////女频粉丝榜
		'index_free'    		=>  array('txtxiaoshuo_bangindex_free_newhongshu',1,1),//首页免费费榜
		'index_nan_free'    	=>  array('txtxiaoshuo_bangindex_nan_free_newhongshu',1,1),//男免费榜
		'index_nv_free'     	=>  array('txtxiaoshuo_bangindex_nv_free_newhongshu',1,1),//女免费榜
		'index_dashen'      	=>  array('txtxiaoshuo_bangindex_dashen_newhongshu',1,1),//首页大神
		'index_nan_dashen'  	=>  array('txtxiaoshuo_bangindex_dashen_nan_newhongshu',1,1),//男大神
		'index_nv_dashen'   	=>  array('txtxiaoshuo_bangindex_dashen_nv_newhongshu',1,1),//女大神
		'index_wanben'      	=>  array('txtxiaoshuo_bangindex_wanben_newhongshu',1,1),//首页完本
		'index_nan_wanben'  	=>  array('txtxiaoshuo_bangindex_wanben_nan_newhongshu',1,1),//男完本
	    'index_nv_wanben'   	=>  array('txtxiaoshuo_bangindex_wanben_nv_newhongshu',1,1),//女完本
	    'ticketrank_nan_total'	=>  array('txtxiaoshuo_bangauto_top_nan_redticket',1,1),//男红票总
	    'ticketrank_nv_total'	=>  array('txtxiaoshuo_bangauto_top_nv_redticket',1,1),//女红票总
        'sales_nan_total'		=>  array('txtxiaoshuo_bangauto_top_nan_totalhotsales',1,1),//男销售总
        'sales_nv_total'		=>  array('txtxiaoshuo_bangauto_top_nv_totalhotsales',1,1),//女销售总
        'sales_nan_month'		=>  array('txtxiaoshuo_bangauto_class_nan_monthhotsales',1,1),//男销售月
        'sales_nv_month'		=>  array('txtxiaoshuo_bangauto_class_nv_monthhotsales',1,1),//女销售月
        'sales_nan_week'		=>  array('txtxiaoshuo_bangauto_class_nan_weekhotsales',1,1),//男销售周
        'sales_nv_week'			=>  array('txtxiaoshuo_bangauto_class_nv_weekhotsales',1,1),//女销售周
        'update_nan_month'		=>  array('txtxiaoshuo_bangauto_top_nan_monthupdate',1,1),//男更新月
        'update_nv_month'		=>  array('txtxiaoshuo_bangauto_top_nv_monthupdate',1,1),//女更细月
        'update_nan_week'		=>  array('txtxiaoshuo_bangauto_top_nan_weekupdate',1,1),//男更新周
        'update_nv_week'		=>  array('txtxiaoshuo_bangauto_top_nv_weekupdate',1,1),//女更新周
        'fav_nan_total'			=>  array('txtxiaoshuo_bangauto_top_nan_totalfav',1,1),//男收藏总
        'fav_nv_total'			=>  array('txtxiaoshuo_bangauto_top_nv_totalfav',1,1),//女收藏总
        'fav_nan_month'			=>  array('txtxiaoshuo_bangauto_class_nan_monthfav',1,1),//男收藏月
        'fav_nv_month'			=>  array('txtxiaoshuo_bangauto_class_nv_monthfav',1,1),//女收藏月
        'fav_nan_week'			=>  array('txtxiaoshuo_bangauto_class_nan_weekfav',1,1),//男收藏周
        'fav_nv_week'			=>  array('txtxiaoshuo_bangauto_class_nv_weekfav',1,1),//女收藏周
        'hit_nan_total'			=>  array('txtxiaoshuo_bangauto_top_nan_totalhit',1,1),//男点击总
        'hit_nv_total'			=>  array('txtxiaoshuo_bangauto_top_nv_totalhit',1,1),//女点击总
        'hit_nan_month'			=>  array('txtxiaoshuo_bangauto_class_nan_monthhit',1,1),//男点击月
        'hit_nv_month'			=>  array('txtxiaoshuo_bangauto_class_nv_monthhit',1,1),//女点击月
        'hit_nan_week'			=>  array('txtxiaoshuo_bangauto_class_nan_weekhit',1,1),//男点击周
        'hit_nv_week'			=>  array('txtxiaoshuo_bangauto_class_nv_weekhit',1,1),//女点击周
        'flower_nan_total'		=>  array('txtxiaoshuo_bangauto_top_nan_totalflower',1,1),//男鲜花总
        'flower_nv_total'		=>  array('txtxiaoshuo_bangauto_top_nv_totalflower',1,1),//女鲜花总
        'flower_nan_month'		=>  array('txtxiaoshuo_bangauto_class_nan_monthflower',1,1),//男鲜花月
        'flower_nv_month'		=>  array('txtxiaoshuo_bangauto_class_nv_monthflower',1,1),//女鲜花月
        'flower_nan_week'		=>  array('txtxiaoshuo_bangauto_class_nan_weekflower',1,1),//男鲜花周
        'flower_nv_week'		=>  array('txtxiaoshuo_bangauto_class_nv_weekflower',1,1),//女鲜花周
        'fansrec_nan_total'		=>  array('txtxiaoshuo_bangauto_top_nan_totalfansrec',1,1),//男粉丝推荐总
        'fansrec_nv_total'		=>  array('txtxiaoshuo_bangauto_top_nv_totalfansrec',1,1),//女粉丝推荐总
        'fansrec_nan_month'		=>  array('txtxiaoshuo_bangauto_top_nan_monthfansrec',1,1),//男粉丝推荐月
        'fansrec_nv_month'		=>  array('txtxiaoshuo_bangauto_top_nv_monthfansrec',1,1),//女粉丝推荐月
        'fansrec_nan_week'		=>  array('txtxiaoshuo_bangauto_top_nan_weekfansrec',1,1),//男粉丝推荐周
        'fansrec_nv_week'		=>  array('txtxiaoshuo_bangauto_top_nv_weekfansrec',1,1),//女粉丝推荐周
        'help_readtopfaq'		=>  array('txtxiaoshuo_newstaticfilelistreadtopfaq',1,1),//读者常见问题top10
        'help_readnewfaq'		=>  array('txtxiaoshuo_newstaticfilelistreadnewfaq',1,1),//读者最新问题
        'help_bbsrule'			=>  array('txtxiaoshuo_newstaticfilelistbbsrule',1,1),//红薯网社区规则
        'help_webfaq'			=>  array('txtxiaoshuo_newstaticfilelistwebfaq',1,1),//网页版问题
        'help_mobilefaq'		=>  array('txtxiaoshuo_newstaticfilelistmobilefaq',1,1),//手机版问题
        'help_rarefaq'			=>  array('txtxiaoshuo_newstaticfilelistrarefaq',1,1),//其他疑难问题
        'help_readfeedback'		=>  array('txtxiaoshuo_newstaticfilelistreadfeedback',1,1),//读者反馈和意见
        'help_authortopfaq'		=>  array('txtxiaoshuo_newstaticfilelistauthortopfaq',1,1),//作者常见问题top10
        'help_authornewfaq'		=>  array('txtxiaoshuo_newstaticfilelistauthornewfaq',1,1),//作者最新问题
        'help_authorwelfare'	=>  array('txtxiaoshuo_newstaticfilelistauthorwelfare',1,1),//作者权益和福利
        'help_authorfeedback'	=>  array('txtxiaoshuo_newstaticfilelistauthorfeedback',1,1),//
		'help_otherhelp'		=>  array('txtxiaoshuo_newstaticfilelistotherhelp',1,1),//其他帮助
		'help_news'	        	=>  array('txtxiaoshuo_newstaticfilelistnews',1,1),//新闻
		'help_indexnotice'		=>  array('txtxiaoshuo_newstaticfilelistgonggao',1,1),//首页通告
		'help_nannotice'		=>  array('txtxiaoshuo_newstaticfilelistgonggao_nan',1,1),//男频通告
		'help_nvnotice'	    	=>  array('txtxiaoshuo_newstaticfilelistgonggao_nv',1,1),//女频通告
		'help_zuozhenotice'		=>  array('txtxiaoshuo_newstaticfilelistgonggao_zuozhe',1,1),//作者通告
        'help_nanfulinotice'	=>  array('txtxiaoshuo_newstaticfilelistgonggao_nanfuli',1,1),//男生福利通告
        'help_nvfulinotice'		=>  array('txtxiaoshuo_newstaticfilelistgonggao_nvfuli',1,1),//女生福利通告
        'help_dreamnotice'		=>  array('txtxiaoshuo_newstaticfilelistgonggao_dreamfactory',1,1),//梦工厂公告
        'help_chubannotice'		=>  array('txtxiaoshuo_newstaticfilelistgonggao_chuban',1,1),//出版公告
        'help_wangbiannotice'	=>  array('txtxiaoshuo_newstaticfilelistgonggao_wangbian',1,1),//网编首页公告
        'help_zhenwennotice'	=>  array('txtxiaoshuo_newstaticfilelistgonggao_zhengwen',1,1),//征文公告
        'findpwdcode'           =>  array('findpwdcode', 0, 0),
        'phonevalidcode'        =>  array('phonevalidcode', 0, 0),
        'paycontrol'			=>  array('hongshu_control_switch', 1, 1),
        'index_ad_nan'	        =>  array('txtxiaoshuo_bangstatic_gg_nan_index1', 1, 1),
        'index_ad_nv'	        =>  array('txtxiaoshuo_bangstatic_gg_nv_index1', 1, 1),
        'nanindex_ad_rm'        =>  array('txtxiaoshuo_bangstatic_gg_nanindex_rm', 1, 1),
        'nanindex_ad_jp'	    =>  array('txtxiaoshuo_bangstatic_gg_nanindex_jp', 1, 1),
        'nvindex_ad_rm'     	=>  array('txtxiaoshuo_bangstatic_gg_nvindex_rm', 1, 1),
        'nvindex_ad_jp'		    =>  array('txtxiaoshuo_bangstatic_gg_nvindex_jp', 1, 1),
        'ad_nan_read'	     	=>  array('txtxiaoshuo_bangstatic_gg_nan_read', 1, 1),
        'ad_nv_read'	     	=>  array('txtxiaoshuo_bangstatic_gg_nv_read', 1, 1),
        'ad_nan_pl'	     		=>  array('txtxiaoshuo_bangstatic_gg_nanbook_pl', 1, 1),
        'ad_nan_dh'	     		=>  array('txtxiaoshuo_bangstatic_gg_nanbook_dh', 1, 1),
        'ad_nv_pl'	     		=>  array('txtxiaoshuo_bangstatic_gg_nvbook_pl', 1, 1),
        'ad_nv_dh'	     		=>  array('txtxiaoshuo_bangstatic_gg_nvbook_dh', 1, 1),
        'ad_index_dh'     		=>  array('txtxiaoshuo_bangstatic_gg_dh_index', 1, 1),
        'ad_nanindex_dh'   		=>  array('txtxiaoshuo_bangstatic_gg_nanindex_dh', 1, 1),
        'ad_nvindex_dh'    		=>  array('txtxiaoshuo_bangstatic_gg_nvindex_dh', 1, 1),
        'ad_nan_ml'		   		=>  array('txtxiaoshuo_bangstatic_gg_ml_nan', 1, 1),
        'ad_nv_ml'                      =>  array('txtxiaoshuo_bangstatic_gg_ml_nv', 1, 1),
        'famous_total'                      =>  array('txtxiaoshuo_bangauto_top_zy_mingjia', 1, 1),
        'famous_nan'                      =>  array('txtxiaoshuo_bangauto_top_zy_mingjia_nan', 1, 1),
        'famous_nv'                      =>  array('txtxiaoshuo_bangauto_top_zy_mingjia_nv', 1, 1),
	)
);
